services:
  mongo:
    image: mongo:4.4
    container_name: dnd_mongo_dev
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-changeme}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME:-dnd_monster_data}
    ports:
      - '27017:27017'
    volumes:
      - mongo_data_dev:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  web:
    build: .
    container_name: dnd_web_dev
    restart: always
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_PASS=${MONGO_INITDB_ROOT_PASSWORD:-changeme}
      - MONGO_DB=${MONGO_DB_NAME:-dnd_monster_data}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    depends_on:
      - mongo

volumes:
  mongo_data_dev:
